services:
  - type: web
    name: proxyagent
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn dashboard:app"
    envVars:
      - key: PORT
        value: 5050